version: "3.7"

services:
  app:
    build:
      context: ./app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
volumes:
  sqlite:
